Attribute VB_Name = "gen_file"
Option Explicit

Public Function genDefaultProfile()
Const ForReading = 1, ForWriting = 2
Dim fso, f
Dim filepath As String
        
If MsgBox("Current default.cfg will be overwritten if exists, are you sure?" + Chr(13) + Chr(13) + _
           "现有default.cfg（若存在）将被覆盖，是否确定？" _
          , vbYesNo + vbDefaultButton2) = vbYes Then
          
       
          

        filepath = App.Path + "\default.cfg"

        Set fso = CreateObject("Scripting.FileSystemObject")
        Set f = fso.OpenTextFile(filepath, ForWriting, True)
        '************************************
        'start:
        
        
f.writeline "//******************************************************************"
f.writeline "//This file is generated by Joystick To H-shifter 2"
f.writeline "//"
f.writeline "//This is the default profile, with options set on default values."
f.writeline "//Joystick To H-shifter 2 can be run without this file."
f.writeline "//But if the file exists, Joystick To H-shifter 2 will load this "
f.writeline "//file as the start up profile."
f.writeline "//You can change the options here for your most played game."
f.writeline "//"
f.writeline "//You can also create another default.cfg "
f.writeline "//by clicking SaveFile&option/Profile/Save..."
f.writeline "//"
f.writeline "//Feel free to contact me for help:"
f.writeline "//Kane Xu, shikai.xu@hotmail.com"
f.writeline "//*******************************************************************"
f.writeline ""
f.writeline "DEVID=0" + Chr(9) + "" + Chr(9) + "//device ID of your joystick in Windows"
f.writeline "PRSHD=1" + Chr(9) + "" + Chr(9) + "//1=Press and Hold, " + Chr(9) + "" + Chr(9) + "0=Press than release"
f.writeline "AUTOC=0" + Chr(9) + "" + Chr(9) + "//1=auto center joystick," + Chr(9) + "0=non-auto center joystick"
f.writeline "LFSVK=0" + Chr(9) + "" + Chr(9) + "//1=LFS," + Chr(9) + "" + Chr(9) + "" + Chr(9) + "0=other directX games"
f.writeline "NGEAR=0" + Chr(9) + "" + Chr(9) + "//1=press virtual key while joystick is in natural gear," + Chr(9) + "0=ignore that"
f.writeline "RGEAR=0" + Chr(9) + "" + Chr(9) + "//1=reverse gear exists," + Chr(9) + "0=no reverse gear"
f.writeline ""
f.writeline "X0MIN=0"
f.writeline "X0MAX=65535"
f.writeline "Y0MIN=30000"
f.writeline "Y0MAX=35535"
f.writeline ""
f.writeline "X1MIN=0"
f.writeline "X1MAX=5000"
f.writeline "Y1MIN=0"
f.writeline "Y1MAX=5000"
f.writeline ""
f.writeline "X2MIN=0"
f.writeline "X2MAX=5000"
f.writeline "Y2MIN=60535"
f.writeline "Y2MAX=65535"
f.writeline ""
f.writeline "X3MIN=10000"
f.writeline "X3MAX=55535"
f.writeline "Y3MIN=0"
f.writeline "Y3MAX=5000"
f.writeline ""
f.writeline "X4MIN=10000"
f.writeline "X4MAX=55535"
f.writeline "Y4MIN=60535"
f.writeline "Y4MAX=65535"
f.writeline ""
f.writeline "X5MIN=60535"
f.writeline "X5MAX=65535"
f.writeline "Y5MIN=0"
f.writeline "Y5MAX=5000"
f.writeline ""
f.writeline "X6MIN=60535"
f.writeline "X6MAX=65535"
f.writeline "Y6MIN=60535"
f.writeline "Y6MAX=65535"
f.writeline ""
f.writeline "X7MIN=58034"
f.writeline "X7MAX=58035"
f.writeline "Y7MIN=65534"
f.writeline "Y7MAX=65535"
f.writeline ""
f.writeline "//*******************************************************************"
f.writeline "//This is the end of file."
f.writeline ""
        
       
        
        'end
        '-------------------------------------
        f.Close
        
        If FileLen(filepath) = 1506 Then MsgBox "default.cfg successfully created." + Chr(13) + Chr(13) + "default.cfg已生成。"



Else
End If
End Function




Public Function genDefaultKeyfile()
Const ForReading = 1, ForWriting = 2
Dim fso, f
Dim filepath As String
        
If MsgBox("Current key.cfg will be overwritten if exists, are you sure?" + Chr(13) + Chr(13) + _
           "现有key.cfg（若存在）将被覆盖，是否确定？" _
          , vbYesNo + vbDefaultButton2) = vbYes Then
          
       
          

        filepath = App.Path + "\key.cfg"

        Set fso = CreateObject("Scripting.FileSystemObject")
        Set f = fso.OpenTextFile(filepath, ForWriting, True)
        '************************************
        'start:
        

f.writeline "//******************************************************************"
f.writeline "//This file is generated by Joystick To H-shifter 2"
f.writeline "//"
f.writeline "//This file stores the default key settings."
f.writeline "//Joystick To H-shifter 2 can be run without this file."
f.writeline "//But if the file exists, Joystick To H-shifter 2 will load this "
f.writeline "//file as the start up key settings."
f.writeline "//You can change the key codes here."
f.writeline "//"
f.writeline "//For the list of the key code, please read the help."
f.writeline "//Don't forget to change the key assignments in game to match the key"
f.writeline "//you've set here."
f.writeline "//"
f.writeline "//Feel free to contact me for help:"
f.writeline "//Kane Xu, shikai.xu@hotmail.com"
f.writeline "//*******************************************************************"
f.writeline "//Keys for DirectX Games:"
f.writeline "//(Using Scan Code)"
f.writeline "DXGG0=&HB  //key 0"
f.writeline "DXGG1=&HA  //key 9"
f.writeline "DXGG2=&H9  //key 8"
f.writeline "DXGG3=&H8  //key 7"
f.writeline "DXGG4=&H7  //key 6"
f.writeline "DXGG5=&H6  //key 5"
f.writeline "DXGG6=&H5  //key 4"
f.writeline "DXGG7=&H4  //key 3"
f.writeline ""
f.writeline ""
f.writeline "//Keys for LFS:"
f.writeline "//(Using Virtual Code)"
f.writeline "LFSG0=&H39 //key 0 (Natural Gear is not used in LFS)"
f.writeline "LFSG1=&H39 //key 9"
f.writeline "LFSG2=&H38 //key 8"
f.writeline "LFSG3=&H37 //key 7"
f.writeline "LFSG4=&H36 //key 6"
f.writeline "LFSG5=&H35 //key 5"
f.writeline "LFSG6=&H30 //key 0"
f.writeline "LFSG7=&H37 //key 7"
f.writeline ""
f.writeline "//*******************************************************************"
f.writeline "//This is the end of file."
f.writeline ""
f.writeline ""
        
       
        
        'end
        '-------------------------------------
        f.Close
        
        If FileLen(filepath) = 1506 Then MsgBox "default.cfg successfully created." + Chr(13) + Chr(13) + "default.cfg已生成。"



Else
End If
End Function
